name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          qtbase5-dev \
          qtdeclarative5-dev \
          qtquickcontrols2-5-dev \
          xvfb \
          libxcb-xinerama0

    - name: Set up XVFB
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 3

    - name: Build with qmake
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Run tests
      run: |
        export DISPLAY=:99
        cd build
        ./MyUnitTestProject # نام فایل اجرایی تست‌ها
